const {
  version,
  DOM,
  PropTypes,
  Children,
  render,
  createClass,
  createFactory,
  createElement,
  cloneElement,
  isValidElement,
  findDOMNode,
  unmountComponentAtNode,
  Component,
  PureComponent,
  unstable_renderSubtreeIntoContainer,
  __spread,
} = require('preact-compat');
const { createContext } = require('preact-context');

module.exports = {
  version,
  DOM,
  PropTypes,
  Children,
  render,
  createClass,
  createFactory,
  createElement,
  cloneElement,
  isValidElement,
  findDOMNode,
  unmountComponentAtNode,
  Component,
  PureComponent,
  unstable_renderSubtreeIntoContainer,
  __spread,
  createContext,
};
